<?php

namespace Ositel\TresorerieBundle\Repository;

/**
 * Transaction_TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Transaction_TagRepository extends \Doctrine\ORM\EntityRepository
{
}
